import axios from "axios";
import * as cheerio from "cheerio";

// Blogger API Config
const API_KEY = process.env.AIzaSyC-QnGpRQX9OlDiOEfr-xAGVCW36eHqIfI;   // set in GitHub Secrets
const BLOG_ID = process.env.3603771571155556347;   // set in GitHub Secrets

// Ad Code
const AD_CODE = `
<script type="text/javascript">
  atOptions = {
    'key' : '11d979eb769afd0a285fed6583d0fa55',
    'format' : 'iframe',
    'height' : 60,
    'width' : 468,
    'params' : {}
  };
</script>
<script type="text/javascript" src="//www.highperformanceformat.com/11d979eb769afd0a285fed6583d0fa55/invoke.js"></script>
`;

// Example URLs (replace with sitemap.txt converted array)
const urls = [
  "https://www.bluelankatours.com/blog/sri-lanka-familys-perfect-holiday",
  "https://www.bluelankatours.com/blog/international-magazine-ranking",
  "https://www.bluelankatours.com/blog/white-water-rafting",
  "https://www.bluelankatours.com/blog/sri-lankan-must-try-foods",
  "https://www.bluelankatours.com/blog/sri-lanka-public-holidays-2017",
  "https://www.bluelankatours.com/blog/experience-extra-special-luxury-holiday-sri-lanka",
  "https://www.bluelankatours.com/blog/simply-flying-experience-sri-lankan-scenery",
  "https://www.bluelankatours.com/blog/tips-perfect-honeymoon-sri-lanka",
  "https://www.bluelankatours.com/blog/expect-sri-lanka-luxury-holidays",
  "https://www.bluelankatours.com/blog/southeast-asia-backpackers-paradise",
  "https://www.bluelankatours.com/blog/tourism-comparison-sri-lanka-maldives",
  "https://www.bluelankatours.com/blog/sri-lankas-beautiful-collection-flora",
  "https://www.bluelankatours.com/blog/tips-planning-tailor-made-holidays-sri-lanka",
  "https://www.bluelankatours.com/blog/advantages-booking-inclusive-sri-lanka-holiday",
  "https://www.bluelankatours.com/blog/best-places-visit-sri-lanka",
  "https://www.bluelankatours.com/blog/5-small-luxury-hotels-southern-coast-sri-lanka",
  "https://www.bluelankatours.com/blog/underground-campaign",
  "https://www.bluelankatours.com/blog/2017-year-spa-holidays",
  "https://www.bluelankatours.com/blog/2016-seasons-greetings-sri-lanka",
  "https://www.bluelankatours.com/blog/sri-lankas-happening-eventsholidays-2017",
  "https://www.bluelankatours.com/blog/go-sri-lanka",
  "https://www.bluelankatours.com/blog/explore-cultural-triangle-sri-lanka",
  "https://www.bluelankatours.com/blog/exciting-air-taxi-experience-sri-lanka",
  "https://www.bluelankatours.com/blog/eight-admirably-exclusive-waterfalls-sri-lanka",
  "https://www.bluelankatours.com/blog/20-reasons-tourists-like-visit-sri-lanka",
  "https://www.bluelankatours.com/blog/experience-geoffrey-bawa-architecture-sri-lanka",
  "https://www.bluelankatours.com/blog/ideal-camping-spots-sri-lanka",
  "https://www.bluelankatours.com/blog/sri-lanka-adventurous-holiday",
  "https://www.bluelankatours.com/blog/six-innovative-ideas-holiday-sri-lanka",
  "https://www.bluelankatours.com/blog/experiencing-sri-lankan-nature-true-luxury-fashion",
  "https://www.bluelankatours.com/blog/top-five-west-coast-tourist-hotspots-sri-lanka",
  "https://www.bluelankatours.com/blog/sri-lankan-airport-will-soon-better-place",
  "https://www.bluelankatours.com/blog/unique-experience-kandy-perahera",
  "https://www.bluelankatours.com/blog/top-five-exclusive-landscapes-sri-lanka",
  "https://www.bluelankatours.com/blog/quick-guide-jaffna-tourism",
  "https://www.bluelankatours.com/blog/five-adventurous-things-ella",
  "https://www.bluelankatours.com/blog/marvels-galle-dutch-fort",
  "https://www.bluelankatours.com/blog/minneriya-national-park-great-gathering",
  "https://www.bluelankatours.com/blog/exploring-wilpattu-national-park",
  "https://www.bluelankatours.com/blog/leopards-yala-national-park",
  "https://www.bluelankatours.com/blog/stilt-fishing-sri-lankan-tradition-time",
  "https://www.bluelankatours.com/blog/5-tips-beat-heat-sri-lanka",
  "https://www.bluelankatours.com/blog/international-vesak-day-celebrations-sri-lanka",
  "https://www.bluelankatours.com/blog/interesting-statistics-dambulla-caves-temple",
  "https://www.bluelankatours.com/blog/experiencing-visit-temple-tooth-kandy",
  "https://www.bluelankatours.com/blog/horton-plains-national-park",
  "https://www.bluelankatours.com/blog/best-turtle-experience-turtle-hatcheries-sri-lanka",
  "https://www.bluelankatours.com/blog/truth-glamping-gal-oya-lodge",
  "https://www.bluelankatours.com/blog/meditation-centers-sri-lanka",
  "https://www.bluelankatours.com/blog/see-vesak-celebrations-colombo",
  "https://www.bluelankatours.com/blog/eighth-wonder-world-sri-lanka",
  "https://www.bluelankatours.com/blog/options-accommodation-sri-lanka",
  "https://www.bluelankatours.com/blog/need-know-ancient-city-anuradhapura",
  "https://www.bluelankatours.com/blog/highlights-polonnaruwa-ancient-city",
  "https://www.bluelankatours.com/blog/ultimate-guide-transport-sri-lanka",
  "https://www.bluelankatours.com/blog/7-sri-lankan-delicacies-not-missed",
  "https://www.bluelankatours.com/blog/celebrate-halloween-sri-lanka",
  "https://www.bluelankatours.com/blog/kids-leisure-spots-sri-lanka",
  "https://www.bluelankatours.com/blog/honeymoon-srilanka-guide",
  "https://www.bluelankatours.com/blog/7-time-favorite-waterfalls-sri-lanka",
  "https://www.bluelankatours.com/blog/8-unesco-world-heritage-sites-sri-lanka",
  "https://www.bluelankatours.com/blog/spot-sri-lankas-spectacular-big-five-mammals",
  "https://www.bluelankatours.com/blog/budget-beach-accommodation-options-sri-lanka",
  "https://www.bluelankatours.com/blog/10-exciting-day-tour-options-sri-lanka",
  "https://www.bluelankatours.com/blog/five-coming-destinations-relaxing-holiday-sri-lanka",
  "https://www.bluelankatours.com/blog/10-perfect-camping-spots-sri-lanka-couples",
  "https://www.bluelankatours.com/blog/7-reasons-not-plan-five-day-holiday-sri-lanka",
  "https://www.bluelankatours.com/blog/best-ways-enjoy-family-day-outing-sri-lanka",
  "https://www.bluelankatours.com/blog/7-best-bucket-list-activities-colombo-sri-lanka",
  "https://www.bluelankatours.com/blog/complete-guide-galle-sri-lanka",
  "https://www.bluelankatours.com/blog/best-places-dine-sri-lanka",
  "https://www.bluelankatours.com/blog/7-best-water-sport-activities-sri-lanka",
  "https://www.bluelankatours.com/blog/ideal-itinerary-discover-sri-lanka-5-days",
  "https://www.bluelankatours.com/blog/try-perfectly-crispy-appam-hoppers-sri-lanka",
  "https://www.bluelankatours.com/blog/fun-adventure-trincomalee-sri-lanka",
  "https://www.bluelankatours.com/blog/10-reasons-must-plan-month-long-holiday-sri-lanka",
  "https://www.bluelankatours.com/blog/trekking-tracks-sri-lanka",
  "https://www.bluelankatours.com/blog/24-hours-colombo-heres-spend",
  "https://www.bluelankatours.com/blog/sri-lankan-cuisine-centers-around-rice-delectable-dishes",
  "https://www.bluelankatours.com/blog/five-romantic-luxury-getaways-valentines-day-2018-sri-lanka",
  "https://www.bluelankatours.com/blog/discover-hills-sri-lanka-train",
  "https://www.bluelankatours.com/blog/tourism-sri-lanka-getting-better",
  "https://www.bluelankatours.com/blog/4-exciting-reasons-cricket-fans-visit-sri-lanka",
  "https://www.bluelankatours.com/blog/best-ice-cream-joints-sri-lanka",
  "https://www.bluelankatours.com/blog/connecting-sri-lanka-anywhere-world",
  "https://www.bluelankatours.com/blog/ultimate-guide-shop-till-drop-sri-lanka",
  "https://www.bluelankatours.com/blog/ideal-jeep-safari-experience-sri-lanka",
  "https://www.bluelankatours.com/blog/spice-holiday-mirissa-sri-lanka",
  "https://www.bluelankatours.com/blog/exciting-christmas-activities-around-hotels-sri-lanka",
  "https://www.bluelankatours.com/blog/public-holidays-sri-lanka-upcoming-year-2018",
  "https://www.bluelankatours.com/blog/choose-blue-lanka-tours-next-tailor-made-holiday-sri-lanka",
  "https://www.bluelankatours.com/blog/adams-peak-ultimate-guide",
  "https://www.bluelankatours.com/blog/rise-coffee-tea-culture-sri-lanka",
  "https://www.bluelankatours.com/blog/7-secret-beach-escapades-sri-lanka",
  "https://www.bluelankatours.com/blog/spotted-deer-common-wild-mammal-seen-sri-lanka",
  "https://www.bluelankatours.com/blog/pastry-sri-lankan-junk-food",
  "https://www.bluelankatours.com/blog/glimpse-enlivening-meemure",
  "https://www.bluelankatours.com/blog/kitulgala-rainforest-reserve-adventurous-traveler",
  "https://www.bluelankatours.com/blog/tale-legendary-manning-market-colombo",
  "https://www.bluelankatours.com/blog/wild-coast-tented-lodge",
  "https://www.bluelankatours.com/blog/thotalagala-bungalow",
  "https://www.bluelankatours.com/blog/havent-sri-lanka-yet-must",
  "https://www.bluelankatours.com/blog/sri-lanka-paradise-surfers-safari-seekers-alike",
  "https://www.bluelankatours.com/blog/sri-lanka-interesting-statistics",
  "https://www.bluelankatours.com/blog/sri-lanka-state-emergency-not-threat-tourists",
  "https://www.bluelankatours.com/blog/illustrations-buddhist-heritage-tourism-sri-lanka",
  "https://www.bluelankatours.com/blog/discover-ancient-cities-sri-lanka",
  "https://www.bluelankatours.com/blog/makes-sri-lanka-three-one-holiday-destination",
  "https://www.bluelankatours.com/blog/feel-aluth-avurudu-new-year-sri-lanka",
  "https://www.bluelankatours.com/blog/migrant-bird-specialties-bundala-national-park",
  "https://www.bluelankatours.com/blog/detoxify-rejuvenate-santani-wellness-resort-spa",
  "https://www.bluelankatours.com/blog/wilpattu-national-park",
  "https://www.bluelankatours.com/blog/christmas-sri-lankans-april",
  "https://www.bluelankatours.com/blog/buckingham-place-tangalle",
  "https://www.bluelankatours.com/blog/a-journey-through-the-wild-side-in-sri-lanka",
  "https://www.bluelankatours.com/blog/10-of-the-best-ways-to-enjoy-sri-lanka",
  "https://www.bluelankatours.com/blog/the-importance-of-rice-in-sri-lanka",
  "https://www.bluelankatours.com/blog/honeymoon-without-the-in-sri-lanka",
  "https://www.bluelankatours.com/blog/fantastic-beasts-marine-mammals-on-the-loose-they-are-coming-for-you",
  "https://www.bluelankatours.com/blog/adventure-at-its-best-the-deep-jungle-festival-31st-aug-2nd-sep-2018",
  "https://www.bluelankatours.com/blog/rumassala-one-of-the-many-japanese-peace-pagodas-across-the-world",
  "https://www.bluelankatours.com/blog/shangri-la-hotel-colombo",
  "https://www.bluelankatours.com/blog/heritance-kandalama",
  "https://www.bluelankatours.com/blog/find-best-rice-curry-experiences-sri-lanka",
  "https://www.bluelankatours.com/blog/surf-stay-paper-moon-kudils-arugam-bay",
  "https://www.bluelankatours.com/blog/july-2018-entertainment-around-sri-lanka",
  "https://www.bluelankatours.com/blog/its-time-to-taste-the-exotic-seasonal-fruits-of-sri-lanka",
  "https://www.bluelankatours.com/blog/discover-a-true-railroad-experience-at-the-idalgashinna-railway-station",
  "https://www.bluelankatours.com/blog/experience-the-best-of-ayurvedic-spas-in-sri-lanka",
  "https://www.bluelankatours.com/blog/10-best-nightlife-experiences-in-colombo",
  "https://www.bluelankatours.com/blog/20-essential-things-to-see-and-do-in-colombo",
  "https://www.bluelankatours.com/blog/exotic-creations-from-the-potters-wheel",
  "https://www.bluelankatours.com/blog/melting-pot-of-faiths",
  "https://www.bluelankatours.com/blog/most-happening-shopping-malls-precincts-in-colombo-sri-lanka",
  "https://www.bluelankatours.com/blog/health-matters-get-your-shots-and-travel-healthy",
  "https://www.bluelankatours.com/blog/a-walk-through-the-astounding-bawa-architecture-in-sri-lanka",
  "https://www.bluelankatours.com/blog/welcome-to-the-magical-tropics-the-island-of-two-separate-monsoons",
  "https://www.bluelankatours.com/blog/embark-into-a-basket-and-delicately-float-away",
  "https://www.bluelankatours.com/blog/a-brief-breakdown-of-visa-categories-and-processes-when-visiting-sri-lanka",
  "https://www.bluelankatours.com/blog/a-tranquil-setting-the-three-temple-loop",
  "https://www.bluelankatours.com/blog/sri-lanka-the-island-of-vibrant-passions",
  "https://www.bluelankatours.com/blog/top-five-reasons-why-you-should-wed-in-sri-lanka",
  "https://www.bluelankatours.com/blog/10-sri-lankan-food-you-must-try",
  "https://www.bluelankatours.com/blog/ceylon-tea-trails-castleregh-bungalow",
  "https://www.bluelankatours.com/blog/ceylon-tea-trails-norwood-bungalow",
  "https://www.bluelankatours.com/blog/ceylon-tea-trails-dunkeld-bungalow",
  "https://www.bluelankatours.com/blog/ceylon-tea-trails-summerville-bungalow",
  "https://www.bluelankatours.com/blog/palmstone-retreat-kithulgala",
  "https://www.bluelankatours.com/blog/heres-why-sri-lanka-ranks-as-lonely-planets-top-country-to-visit-in-2019",
  "https://www.bluelankatours.com/blog/sri-lankas-cultural-triangle-and-what-to-expect",
  "https://www.bluelankatours.com/blog/useful-sri-lanka-travel-info-for-2019",
  "https://www.bluelankatours.com/blog/calling-all-literary-buffs-to-visit-sri-lanka-jan-is-your-month",
  "https://www.bluelankatours.com/blog/sri-lankas-independence-day-celebrations-and-what-to-expect",
  "https://www.bluelankatours.com/blog/heres-why-adams-peek-should-be-on-your-list-of-sri-lanka-must-dos",
  "https://www.bluelankatours.com/blog/useful-things-to-have-in-your-travel-bag-when-travelling-in-sri-lanka",
  "https://www.bluelankatours.com/blog/culture-club-galle-fort",
  "https://www.bluelankatours.com/blog/7-exciting-things-to-do-in-mirissa",
  "https://www.bluelankatours.com/blog/lankan-fishermen-and-their-lifestyle",
  "https://www.bluelankatours.com/blog/best-ways-to-spend-valentines-day-in-sri-lanka",
  "https://www.bluelankatours.com/blog/beneath-ceylonese-beauty-lies-the-precious-sri-lanka-the-island-of-gemstones",
  "https://www.bluelankatours.com/blog/a-turtle-loving-sri-lankan-holiday",
  "https://www.bluelankatours.com/blog/liptons-seat-a-stunning-viewpoint-in-sri-lanka",
  "https://www.bluelankatours.com/blog/why-ella-sri-lanka-must-be-on-your-travel-bucket-list",
  "https://www.bluelankatours.com/blog/10-best-places-to-observe-sunrise-and-sunset-in-sri-lanka",
  "https://www.bluelankatours.com/blog/royal-botanical-gardens-in-kandy-sri-lanka-a-must-visit",
  "https://www.bluelankatours.com/blog/a-soothing-holiday-at-the-stone-house-kandy",
  "https://www.bluelankatours.com/blog/five-things-to-avoid-doing-when-traveling-in-sri-lanka",
  "https://www.bluelankatours.com/blog/the-upcoming-vesak-festival-in-sri-lanka",
  "https://www.bluelankatours.com/blog/the-hiding-temple-kadodara-viharaya-in-kotmale-sri-lanka",
  "https://www.bluelankatours.com/blog/tourists-showing-support-to-promote-a-safe-sri-lanka",
  "https://www.bluelankatours.com/blog/inspirational-ecotourism-at-tri-lanka-koggala",
  "https://www.bluelankatours.com/blog/immerse-into-nature-at-wild-grass-sigiriya",
  "https://www.bluelankatours.com/blog/amongst-top-ten-coastal-retreats-amanwella-resort-tangalle",
  "https://www.bluelankatours.com/blog/satisfy-your-seafood-cravings-in-sri-lanka",
  "https://www.bluelankatours.com/blog/cape-weligama-a-luxurious-escape",
  "https://www.bluelankatours.com/blog/experience-a-private-island-getaway-in-sri-lanka",
  "https://www.bluelankatours.com/blog/march-2019-interesting-events-for-a-better-sri-lanka",
  "https://www.bluelankatours.com/blog/revealing-two-of-ellas-most-well-kept-secrets",
  "https://www.bluelankatours.com/blog/why-choose-cantaloupe-levels-for-your-stay-in-south-sri-lanka",
  "https://www.bluelankatours.com/blog/wild-collective-kalpitiya-not-to-miss-event",
  "https://www.bluelankatours.com/blog/the-magical-sera-ella-falls-in-sri-lanka",
  "https://www.bluelankatours.com/blog/eight-bucket-list-items-to-complete-in-weligama-sri-lanka",
  "https://www.bluelankatours.com/blog/sri-lanka-and-sri-lankans-will-prevail",
  "https://www.bluelankatours.com/blog/elephants-galore-at-udawalawe-national-park",
  "https://www.bluelankatours.com/blog/when-to-travel-where-in-sri-lanka-a-mini-guide",
  "https://www.bluelankatours.com/blog/top-three-coastal-resorts-for-a-family-holiday-in-sri-lanka-2",
  "https://www.bluelankatours.com/blog/undiscovered-natural-treasures-at-gal-oya-national-park",
  "https://www.bluelankatours.com/blog/ayurveda-in-srilanka",
  "https://www.bluelankatours.com/blog/deep-sea-fishing",
  "https://www.bluelankatours.com/blog/next-step-to-your-freedom",
  "https://www.bluelankatours.com/blog/wasgamuwa-national-park",
  "https://www.bluelankatours.com/blog/haputale-misty-town-with-history",
  "https://www.bluelankatours.com/blog/squid-fishing",
  "https://www.bluelankatours.com/blog/sneak-peak-of-srilanka",
  "https://www.bluelankatours.com/blog/lunugamvehera-national-park",
  "https://www.bluelankatours.com/blog/how-to-make-the-most-of-sri-lankas-supposed-off-season",
  "https://www.bluelankatours.com/blog/must-visit-the-all-new-lotus-tower-in-sri-lanka",
  "https://www.bluelankatours.com/blog/spice-up-your-sri-lanka-holiday-by-being-a-part-of-the-england-cricket-tour-of-sri-lanka-2020",
  "https://www.bluelankatours.com/blog/birds-and-more-at-bundala-national-park",
  "https://www.bluelankatours.com/blog/mandaramnuwara-a-mystery-village-waiting-for-the-discerned-traveler",
  "https://www.bluelankatours.com/blog/9-secret-places-in-sri-lanka-that-must-be-explored",
  "https://www.bluelankatours.com/blog/mystical-setting-amidst-wilderness-at-wasgamuwa-national-park",
  "https://www.bluelankatours.com/blog/20-insane-reasons-why-you-should-experience-the-cliff-lodge-in-sri-lanka",
  "https://www.bluelankatours.com/blog/best-producers-of-low-grown-tea-nandana-tea-factory",
  "https://www.bluelankatours.com/blog/be-amazed-with-sri-lankas-largest-shopping-mall-at-one-galle-face",
  "https://www.bluelankatours.com/blog/colombo-port-city-born-from-the-ocean-now-belongs-to-sri-lanka",
  "https://www.bluelankatours.com/blog/must-visit-caves-of-sri-lanka",
  "https://www.bluelankatours.com/blog/a-unique-perspective-sri-lanka-as-a-sailing-destination",
  "https://www.bluelankatours.com/blog/explore-sri-lanka-by-train-a-brief-guide",
  "https://www.bluelankatours.com/blog/7-most-luxurious-things-to-do-in-sri-lanka",
  "https://www.bluelankatours.com/blog/mountain-of-measurement-hikers-paradise",
  "https://www.bluelankatours.com/blog/five-unforgettable-food-scene-experiences-in-sri-lanka",
  "https://www.bluelankatours.com/blog/photogenic-belihuloya-nature-adventures-in-sri-lanka",
  "https://www.bluelankatours.com/blog/dalawella-beach-a-social-media-hotspot-that-drives-tourism-in-sri-lanka",
  "https://www.bluelankatours.com/blog/an-exciting-combination-of-sri-lanka-and-maldives-in-one-holiday",
  "https://www.bluelankatours.com/blog/kataragama-and-its-enchanting-religious-significance",
  "https://www.bluelankatours.com/blog/premium-accommodation-at-the-westbury-palace-little-england",
  "https://www.bluelankatours.com/blog/seven-most-expensive-hotel-rooms-across-the-globe",
  "https://www.bluelankatours.com/blog/eight-most-unique-experiences-of-a-holiday-in-sri-lanka",
  "https://www.bluelankatours.com/blog/seven-most-beautiful-waterfalls-to-visit-in-sri-lanka",
  "https://www.bluelankatours.com/blog/sri-lanka-the-most-generous-country-during-covid19-nas-daily",
  "https://www.bluelankatours.com/blog/11-travel-related-things-to-try-from-home-while-in-quarantine",
  "https://www.bluelankatours.com/blog/comprehensive-guideline-updated-sri-lanka-travel-requirements-from-august-2020",
  "https://www.bluelankatours.com/blog/seven-of-the-most-luxurious-all-inclusive-hotels-in-sri-lanka",
  "https://www.bluelankatours.com/blog/fancy-a-wide-palette-of-honeymoon-destinations-sri-lanka-has-got-you-covered",
  "https://www.bluelankatours.com/blog/tentalows-finest-luxury-camping-sites-in-sri-lanka",
  "https://www.bluelankatours.com/blog/quick-guide-to-the-best-museums-in-sri-lanka",
  "https://www.bluelankatours.com/blog/essential-sri-lanka-travel-tips-and-laws-that-foreigners-should-know-about",
  "https://www.bluelankatours.com/blog/an-archaeological-wonder-the-arankele-monastery-in-sri-lanka",
  "https://www.bluelankatours.com/blog/sri-lankas-third-international-airport-boosts-tourism-opportunities",
  "https://www.bluelankatours.com/blog/all-new-sri-lanka-tour-inspired-by-the-gandys-charity-foundation",
  "https://www.bluelankatours.com/blog/top-10-family-friendly-holiday-destinations-in-sri-lanka",
  "https://www.bluelankatours.com/blog/discover-sri-lanka-like-a-true-sri-lankan",
  "https://www.bluelankatours.com/blog/20-things-to-know-about-sri-lanka",
  "https://www.bluelankatours.com/blog/an-exclusive-mountainous-experience-at-aarunya-resort-kandy",
  "https://www.bluelankatours.com/blog/most-popular-contemporary-fashion-trends-in-sri-lanka",
  "https://www.bluelankatours.com/blog/how-to-be-a-sustainable-traveler-in-sri-lanka",
  "https://www.bluelankatours.com/blog/things-you-are-likely-to-miss-when-you-leave-sri-lanka",
  "https://www.bluelankatours.com/blog/top-tips-for-planning-the-perfect-surfing-holiday-to-sri-lanka",
  "https://www.bluelankatours.com/blog/putting-the-pandemic-behind-us-a-helpful-travel-guide-to-sri-lanka",
  "https://www.bluelankatours.com/blog/enjoy-complete-privacy-at-these-ten-stunning-villas-in-sri-lanka",
  "https://www.bluelankatours.com/blog/top-ten-national-parks-to-visit-in-sri-lanka",
  "https://www.bluelankatours.com/blog/blue-lanka-tours-wins-2020-travelers-choice-award-from-tripadvisor",
  "https://www.bluelankatours.com/blog/blue-lanka-tours-thrilled-to-receive-world-travel-awards-for-sri-lankas-leading-tour-operator-2020",
  "https://www.bluelankatours.com/blog/a-guide-to-purchasing-traditional-souvenirs-in-sri-lanka",
  "https://www.bluelankatours.com/blog/unleashing-five-thrilling-road-trips-in-sri-lanka",
  "https://www.bluelankatours.com/blog/exploring-the-historical-and-cultural-heritage-of-sri-lanka",
  "https://www.bluelankatours.com/blog/colombo-city-transforms-to-a-tourist-hub-in-south-asia",
  "https://www.bluelankatours.com/blog/visit-badulla-to-experience-an-unforgettable-vacation-in-sri-lanka",
  "https://www.bluelankatours.com/blog/discovering-everything-there-is-to-explore-in-colombo",
  "https://www.bluelankatours.com/blog/enjoy-amazing-bird-watching-experiences-in-sri-lanka",
  "https://www.bluelankatours.com/blog/bloomberg-reveals-sigiriya-lions-rock-amongst-the-new-seven-wonders-of-the-world",
  "https://www.bluelankatours.com/blog/the-complete-guide-to-shopping-in-colombo",
  "https://www.bluelankatours.com/blog/seven-hotels-in-sigiriya-you-must-stay-at",
  "https://www.bluelankatours.com/blog/12-dos-and-donts-for-a-memorable-vacation-in-2021",
  "https://www.bluelankatours.com/blog/experience-fun-filled-traditions-of-the-sinhala-and-tamil-new-year-in-sri-lanka",
  "https://www.bluelankatours.com/blog/make-unforgettable-memories-at-some-of-the-finest-honeymoon-places-in-sri-lanka-in-2021",
  "https://www.bluelankatours.com/blog/promising-reasons-why-sri-lanka-is-a-safe-choice-for-post-covid-travel",
  "https://www.bluelankatours.com/blog/stunning-beaches-in-sri-lanka-that-you-must-visit-in-2021",
  "https://www.bluelankatours.com/blog/shopping-in-galle-10-must-visit-boutique-stores",
  "https://www.bluelankatours.com/blog/must-see-nature-and-wildlife-destinations-in-sri-lanka",
  "https://www.bluelankatours.com/blog/2021-travelers-choice-award-once-again-grabbed-by-blue-lanka-tours",
  "https://www.bluelankatours.com/blog/eight-assuring-reasons-why-sri-lanka-is-fantastic-for-kids",
  "https://www.bluelankatours.com/blog/the-dos-and-donts-when-visiting-a-national-park-in-sri-lanka",
  "https://www.bluelankatours.com/blog/things-you-need-to-know-if-you-are-travelling-to-sri-lanka-from-europe",
  "https://www.bluelankatours.com/blog/checklist-of-things-to-do-in-jaffna-when-you-visit-the-sri-lankan-haven",
  "https://www.bluelankatours.com/blog/voluntourism-in-sri-lanka",
  "https://www.bluelankatours.com/blog/the-gloriously-scenic-kandy-to-ella-train",
  "https://www.bluelankatours.com/blog/top-10-romantic-destinations-in-sri-lanka-perfect-for-lovers-or-honeymooners",
  "https://www.bluelankatours.com/blog/why-is-sustainable-travel-important-for-sri-lanka",
  "https://www.bluelankatours.com/blog/ramayana-tour-in-sri-lanka-2022-exploring-the-religious-trail-in-the-island-nation",
  "https://www.bluelankatours.com/blog/uk-travelers-can-now-plan-their-holiday-in-sri-lanka",
  "https://www.bluelankatours.com/blog/07-remarkable-trekking-trails-in-sri-lanka",
  "https://www.bluelankatours.com/blog/explore-sri-lanka-as-a-wreck-diving-treasure-trove",
  "https://www.bluelankatours.com/blog/things-to-do-in-sri-lanka-when-travel-returns-post-covid",
  "https://www.bluelankatours.com/blog/an-ultimate-guide-to-the-pidurangala-rock-hike-in-sigiriya-sri-lanka",
  "https://www.bluelankatours.com/blog/comprehensive-guide-to-an-eco-friendly-holiday-in-sri-lanka",
  "https://www.bluelankatours.com/blog/brief-guide-to-a-thrilling-hot-air-balloon-ride-in-sri-lanka",
  "https://www.bluelankatours.com/blog/sri-lanka-amongst-conde-nast-travelers-list-of-best-countries-in-the-world-2021",
  "https://www.bluelankatours.com/blog/a-complete-guide-to-kitesurfing-in-sri-lanka",
  "https://www.bluelankatours.com/blog/sri-lanka-ranks-among-the-leading-five-wellness-tourism-destinations-for-2021",
  "https://www.bluelankatours.com/blog/wildlife-treasures-at-kaudulla-national-park",
  "https://www.bluelankatours.com/blog/dickwella-the-surf-beach-gem-of-sri-lanka",
  "https://www.bluelankatours.com/blog/highlights-of-kitulgala-a-must-include-in-your-sri-lanka-itinerary",
  "https://www.bluelankatours.com/blog/all-about-the-must-visit-tea-empire-in-nuwara-eliya",
  "https://www.bluelankatours.com/blog/a-complete-travel-guide-to-ella-sri-lanka-including-ten-activities-you-shouldnt-miss",
  "https://www.bluelankatours.com/blog/08-best-couple-activities-to-do-on-your-sri-lanka-honeymoon",
  "https://www.bluelankatours.com/blog/the-ella-odyssey-train",
  "https://www.bluelankatours.com/blog/mihintale-the-cradle-of-sri-lankan-buddhist-civilization",
  "https://www.bluelankatours.com/blog/the-calendar-of-festivals-for-2022-in-sri-lanka",
  "https://www.bluelankatours.com/blog/tour-sri-lanka-with-two-of-the-most-legendary-cricket-teams-in-history",
  "https://www.bluelankatours.com/blog/exciting-sri-lanka-honeymoon-ideas-for-adventurous-couples",
  "https://www.bluelankatours.com/blog/create-your-philanthropic-journey-across-sri-lanka",
  "https://www.bluelankatours.com/blog/essentials-items-when-travelling-to-sri-lanka",
  "https://www.bluelankatours.com/blog/sri-lankas-abundant-inheritance-of-unique-handicrafts",
  "https://www.bluelankatours.com/blog/5-best-beaches-in-sri-lanka-that-would-be-a-regret-to-miss",
  "https://www.bluelankatours.com/blog/10-secret-places-in-sri-lanka-that-must-be-explored",
  "https://www.bluelankatours.com/blog/blue-lanka-tours-re-claims-the-world-travel-award-as-the-leading-tour-operator-in-sri-lanka-for-2022",
  "https://www.bluelankatours.com/blog/15-exciting-water-sports-you-must-try-during-your-trip-to-sri-lanka",
  "https://www.bluelankatours.com/blog/a-comprehensive-guide-to-a-cycling-tour-exploring-the-scenic-beauty-of-sri-lanka",
  "https://www.bluelankatours.com/blog/sri-lanka-updated-travel-restrictions-in-2022",
  "https://www.bluelankatours.com/blog/diyaluma-falls-the-ultimate-guide",
  "https://www.bluelankatours.com/blog/must-visit-iconic-cultural-hotspots-during-your-sri-lanka-trip",
  "https://www.bluelankatours.com/blog/bird-watching-in-sri-lanka",
  "https://www.bluelankatours.com/blog/wasgamuwa-national-park-in-sri-lanka",
  "https://www.bluelankatours.com/blog/kumana-national-park",
  "https://www.bluelankatours.com/blog/gal-oya-national-park",
  "https://www.bluelankatours.com/blog/10-specialties-of-sri-lankas-north-that-make-it-a-must-visit",
  "https://www.bluelankatours.com/blog/how-to-plan-a-luxury-bespoke-tour-in-sri-lanka",
  "https://www.bluelankatours.com/blog/why-sri-lanka-is-an-ideal-holiday-destination-for-sports-enthusiasts",
  "https://www.bluelankatours.com/blog/sri-lanka-in-2023-a-complete-travel-guide",
  "https://www.bluelankatours.com/blog/kalpitiya-the-home-of-dolphin-watching-and-kitesurfing-in-sri-lanka",
  "https://www.bluelankatours.com/blog/from-colombo-to-colombo-and-everything-in-between-with-a-round-tour-of-sri-lanka",
  "https://www.bluelankatours.com/blog/narrowing-down-sri-lankas-top-six-day-tour-itinerary-options",
  "https://www.bluelankatours.com/blog/sri-lanka-by-nature-through-the-eyes-of-a-child",
  "https://www.bluelankatours.com/blog/from-boutique-to-basic-a-guide-to-accommodation-options-in-colombo",
  "https://www.bluelankatours.com/blog/destinations-to-cover-on-a-walking-tour-in-sri-lanka",
  "https://www.bluelankatours.com/blog/azure-fronted-best-breakfast-spots-down-south-in-sri-lanka",
  "https://www.bluelankatours.com/blog/get-closer-to-exotic-nature-at-the-best-camping-sites-in-sri-lanka",
  "https://www.bluelankatours.com/blog/a-day-out-by-some-of-the-visually-stunning-lakes-and-reservoirs-in-sri-lanka",
  "https://www.bluelankatours.com/blog/explore-lotus-tower-the-latest-attraction-in-colombo",
  "https://www.bluelankatours.com/blog/six-exclusive-picnic-appropriate-parks-in-sri-lanka",
  "https://www.bluelankatours.com/blog/pick-sri-lanka-as-your-ultimate-christmas-vacation-in-2022",
  "https://www.bluelankatours.com/blog/exploring-the-current-status-of-tourism-in-sri-lanka",
  "https://www.bluelankatours.com/blog/favorite-spots-to-include-in-a-hiking-itinerary-in-sri-lanka",
  "https://www.bluelankatours.com/blog/why-choose-sri-lanka-as-a-yoga-holiday-destination",
  "https://www.bluelankatours.com/blog/a-guide-to-exploring-the-cultural-triangle-of-sri-lanka",
  "https://www.bluelankatours.com/blog/ten-types-of-purpose-built-tours-in-sri-lanka",
  "https://www.bluelankatours.com/blog/studying-the-unesco-world-heritage-sites-in-sri-lanka",
  "https://www.bluelankatours.com/blog/how-to-arrange-a-tailor-made-holiday-in-sri-lanka",
  "https://www.bluelankatours.com/blog/five-best-places-to-see-elephants-in-sri-lanka",
  "https://www.bluelankatours.com/blog/a-guide-to-the-most-romantic-destinations-in-sri-lanka",
  "https://www.bluelankatours.com/blog/best-hostels-in-weligama-for-a-budget-friendly-stay-in-sri-lanka",
  "https://www.bluelankatours.com/blog/a-guide-to-sri-lankas-summer-season-water-sports",
  "https://www.bluelankatours.com/blog/unveiling-the-best-of-sri-lanka-a-21-day-itinerary-for-ultimate-exploration",
  "https://www.bluelankatours.com/blog/sri-lanka-bike-tour-adventures-and-encounters-on-two-wheels",
  "https://www.bluelankatours.com/blog/top-places-to-visit-in-sri-lanka-on-a-2-day-getaway",
  "https://www.bluelankatours.com/blog/best-picnic-places-in-sri-lanka-to-spend-quality-time-with-your-loved-ones",
  "https://www.bluelankatours.com/blog/the-best-tropical-island-getaway-in-5-days-in-sri-lanka-2",
  "https://www.bluelankatours.com/blog/ahu-bay-serenity-in-sri-lankas-coastal-paradise",
  "https://www.bluelankatours.com/blog/soar-above-serendib-with-heli-tours-in-sri-lanka",
  "https://www.bluelankatours.com/blog/kayaam-house-paradise-at-the-edge-of-the-indian-ocean",
  "https://www.bluelankatours.com/blog/blue-lanka-tours-wins-sri-lankas-leading-tour-operator-third-time-world-travel-awards",
  "https://www.bluelankatours.com/blog/why-sri-lanka-is-one-of-the-worlds-best-destinations-for-safari",
  "https://www.bluelankatours.com/blog/luxury-beyond-compare-experiencing-the-finest-accommodations-in-sri-lanka",
  "https://www.bluelankatours.com/blog/things-to-do-around-sigiriya",
  "https://www.bluelankatours.com/blog/following-the-ramayana-trail-of-sri-lanka",
  "https://www.bluelankatours.com/blog/the-outstanding-universal-value-of-the-sinharaja-rainforest",
  "https://www.bluelankatours.com/blog/the-cultural-legacy-of-the-indigenous-people-of-sri-lanka",
  "https://www.bluelankatours.com/blog/exclusive-guide-for-solo-female-travelers-in-sri-lanka",
  "https://www.bluelankatours.com/blog/how-to-prepare-for-your-holiday-in-sri-lanka",
  "https://www.bluelankatours.com/blog/your-next-santani-experience-kirana-bentota-and-sama-kosgoda",
  "https://www.bluelankatours.com/blog/seeking-serenity-at-the-summit-cliff-top-retreats-in-sri-lanka",
  "https://www.bluelankatours.com/blog/the-pekoe-trail",
  "https://www.bluelankatours.com/blog/embark-on-a-wild-odyssey-top-10-wildlife-experiences-in-sri-lanka",
  "https://www.bluelankatours.com/blog/discover-sri-lankas-secrets-off-the-beaten-path-travel-tips",
  "https://www.bluelankatours.com/blog/what-is-the-best-train-route-to-take-for-the-best-scenery",
  "https://www.bluelankatours.com/blog/the-big-five-tour-of-sri-lanka",
  "https://www.bluelankatours.com/blog/artistic-tour-of-sri-lanka",
  "https://www.bluelankatours.com/blog/putting-your-adrenaline-junkie-hair-down-in-sri-lanka",
  "https://www.bluelankatours.com/blog/must-visit-places-on-the-north-coast-of-sri-lanka",
  "https://www.bluelankatours.com/blog/how-to-travel-responsibly-in-2024",
  "https://www.bluelankatours.com/blog/adding-sri-lanka-to-your-bucket-list-for-2024",
  "https://www.bluelankatours.com/blog/celebrating-milestones-in-sri-lanka",
  "https://www.bluelankatours.com/blog/treating-your-senses-to-the-sri-lankan-culinary-experience",
  "https://www.bluelankatours.com/blog/why-you-should-choose-sri-lanka-for-remote-work-travel",
  "https://www.bluelankatours.com/blog/budget-travelling-in-sri-lanka",
  "https://www.bluelankatours.com/blog/tuk-tuk-safaris-in-colombo-for-a-fresh-new-way-to-sightsee",
  "https://www.bluelankatours.com/blog/child-friendly-holiday-activities-in-sri-lanka",
  "https://www.bluelankatours.com/blog/life-as-a-tour-guide-in-sri-lanka",
  "https://www.bluelankatours.com/blog/free-travel-visa-to-sri-lanka-for-citizens-of-35-countries",
  "https://www.bluelankatours.com/blog/why-is-sri-lanka-a-must-visit-travel-destination",
  "https://www.bluelankatours.com/blog/sri-lanka-among-the-five-fast-growing-tourism-destinations-in-2024",
  "https://www.bluelankatours.com/blog/magnificent-maskeliya-hidden-in-the-mesmeric-mountains",
  "https://www.bluelankatours.com/blog/holistic-healing-under-the-sun-for-the-wellness-break-you-thoroughly-deserve",
  "https://www.bluelankatours.com/blog/journey-through-a-remarkable-history-across-the-ancient-kingdoms-of-sri-lanka",
  "https://www.bluelankatours.com/blog/blooming-smiles-comes-to-kakulbendidigiliya-primary-school",
  "https://www.bluelankatours.com/blog/sri-lanka-in-december-what-to-expect-as-the-high-season-begins",
  "https://www.bluelankatours.com/blog/escaping-to-a-healing-hillside-with-luxury-glenross-living-kalutara",
  "https://www.bluelankatours.com/blog/w15-ambuluwawa-unrivalled-secluded-mountaintop-serenity",
  "https://www.bluelankatours.com/blog/benefits-of-choosing-local-vs-foreign-tour-operators-for-world-travel",
  "https://www.bluelankatours.com/blog/sri-lanka-is-the-worlds-most-desirable-island-voted-by-wanderlust-magazine",
  "https://www.bluelankatours.com/blog/your-introduction-to-the-buzzing-sri-lankan-street-food-scene",
  "https://www.bluelankatours.com/blog/australian-tour-of-sri-lanka-2025-how-to-experience-the-island-cricket-haven",
  "https://www.bluelankatours.com/blog/makandawa-forest-the-lesser-known-rainforest-of-sri-lanka",
  "https://www.bluelankatours.com/blog/sri-lanka-earns-a-worthy-top-10-spot-on-bbcs-25-best-places-to-travel-in-2025",
  "https://www.bluelankatours.com/blog/planning-a-proposal-why-sri-lanka-is-the-one-place-to-make-it-cherishable",
  "https://www.bluelankatours.com/blog/kalpitiya-the-beach-haven-no-one-told-you-about",
  "https://www.bluelankatours.com/blog/top-5-eco-friendly-hotels-of-sri-lanka-promoting-sustainability-with-style",
  "https://www.bluelankatours.com/blog/blue-lanka-tours-pledges-steady-support-to-little-hearts-foundation",
  "https://www.bluelankatours.com/blog/sipping-serenity-in-hatton-misty-peaks-and-endless-tea-fields",
  "https://www.bluelankatours.com/blog/sri-lankas-pekoe-trail-among-time-magazines-2025-worlds-greatest-places",
  "https://www.bluelankatours.com/blog/the-best-surf-spots-in-arugam-bay-to-ride-the-waves-like-a-pro",
  "https://www.bluelankatours.com/blog/immersing-in-the-architectural-and-landscape-creations-of-the-bawas",
  "https://www.bluelankatours.com/blog/a-uniquely-sri-lankan-safari-experience-let-us-take-you-out-of-the-savannah",
  "https://www.bluelankatours.com/blog/souvenirs-from-sri-lanka-collect-the-worlds-most-iconic-mementoes",
  "https://www.bluelankatours.com/blog/reasons-to-visit-the-culturally-diverse-and-nature-rich-chilaw",
  "https://www.bluelankatours.com/blog/visiting-ritigala-monastery-steeped-in-legend-and-mystery",
  "https://www.bluelankatours.com/blog/who-loves-a-tropical-rooftop-bar-these-are-the-best-in-colombo",
  "https://www.bluelankatours.com/blog/ultimate-guide-to-responsible-whale-watching-tours-in-sri-lanka",
  "https://www.bluelankatours.com/blog/prince-williams-guardians-puts-sri-lankas-wildlife-warriors-on-the-global-stage",
  "https://www.bluelankatours.com/blog/unique-attractions-on-sri-lankas-south-coast-that-take-you-off-the-beaten-track",
  "https://www.bluelankatours.com/blog/sri-lankas-unfaltering-resilience-lauded-by-the-british-guild-of-travel-writers",
  "https://www.bluelankatours.com/blog/the-nature-loving-sustainable-and-indigenous-way-of-life-in-bintenna-and-dambana",
  "https://www.bluelankatours.com/blog/wasgamuwa-one-of-the-best-national-parks-in-sri-lanka-for-wild-elephant-sightings",
  "https://www.bluelankatours.com/blog/top-15-must-visit-places-in-sri-lanka-for-first-time-travellers",
  "https://www.bluelankatours.com/blog/a-complete-guide-to-sri-lankas-unesco-world-heritage-sites",
  "https://www.bluelankatours.com/blog/best-beaches-in-sri-lanka-where-to-go-for-sun-surf-and-relaxation",
  "https://www.bluelankatours.com/blog/tuk-tuk-tour-guide-sri-lanka",
  "https://www.bluelankatours.com/blog/best-tea-plantations-factories-sri-lanka",
  "https://www.bluelankatours.com/blog/film-locations-sri-lanka",
  "https://www.bluelankatours.com/blog/story-behind-mount-lavinia-hotel",
  "https://www.bluelankatours.com/blog/climbing-sigiriya-rock-with-kids",
  "https://www.bluelankatours.com/blog/peacocks-in-sri-lanka",
  "https://www.bluelankatours.com/blog/five-unique-pagodas-stupas-to-visit-when-in-sri-lanka",
  "https://www.bluelankatours.com/blog/vegetarian-restaurants-sri-lanka",
  "https://www.bluelankatours.com/blog/must-visit-caves-sri-lanka",
  "https://www.bluelankatours.com/blog/worth-a-visit-nelligala-buddhist-temple",
  "https://www.bluelankatours.com/blog/red-mosque-colombo",
  "https://www.bluelankatours.com/blog/instagrammable-places-sri-lanka",
  "https://www.bluelankatours.com/blog/sea-turtles-sri-lanka",
  "https://www.bluelankatours.com/blog/best-rocks-to-climb-sri-lanka",
  "https://www.bluelankatours.com/blog/tree-house-accommodation-sri-lanka",
  "https://www.bluelankatours.com/blog/historic-hotels-in-sri-lanka",
  "https://www.bluelankatours.com/blog/nil-diya-pokuna",
  "https://www.bluelankatours.com/blog/how-to-make-vesak-lanterns",
  "https://www.bluelankatours.com/blog/solo-travel-sri-lanka",
  "https://www.bluelankatours.com/blog/forests-of-sri-lanka",
  "https://www.bluelankatours.com/blog/babymoon-in-sri-lanka",
  "https://www.bluelankatours.com/blog/family-friendly-sri-lanka-top-activities-for-kids-parents",
  "https://www.bluelankatours.com/blog/sri-lanka-vs-maldives",
  "https://www.bluelankatours.com/blog/how-to-plan-a-sustainable-tour-in-sri-lanka",
  "https://www.bluelankatours.com/blog/sri-lanka-honeymoon-planning-insider-tips-for-couples",
  "https://www.bluelankatours.com/blog/how-to-book-a-private-guide-in-sri-lanka-and-why-it-matters",
  "https://www.bluelankatours.com/blog/off-the-beaten-path-sri-lanka-hidden-gems-most-tourists-miss"
];

async function fetchArticle(url) {
  const res = await axios.get(url);
  const $ = cheerio.load(res.data);

  const title = $("title").first().text().trim() || "Untitled Post";
  let content = $("article").html() || $("body").html();

  // Insert Ads randomly
  let parts = content.split("</p>");
  for (let i = 0; i < 10; i++) {
    let idx = Math.floor(Math.random() * parts.length);
    parts.splice(idx, 0, AD_CODE);
  }
  content = parts.join("</p>");

  return { title, content };
}

async function postToBlogger(title, content) {
  const endpoint = `https://www.googleapis.com/blogger/v3/blogs/${BLOG_ID}/posts/?key=${API_KEY}`;
  const payload = { kind: "blogger#post", title, content };
  const res = await axios.post(endpoint, payload, {
    headers: { "Content-Type": "application/json" }
  });
  console.log(`✅ Posted: ${title}`);
}

async function main() {
  for (const link of urls) {
    try {
      const { title, content } = await fetchArticle(link);
      await postToBlogger(title, content);
      await new Promise(r => setTimeout(r, 10000)); // avoid quota limits
    } catch (err) {
      console.error("❌ Error with", link, err.message);
    }
  }
}

main();
